
const countrylist = [
    { name: 'Afghanistan', dialCode: '+93', Code: 'AF', flag: '🇦🇫' },
    { name: 'Albania', dialCode: '+355', Code: 'AL', flag: '🇦🇱' },
    { name: 'Algeria', dialCode: '+213', Code: 'DZ', flag: '🇩🇿' },
    { name: 'AmericanSamoa', dialCode: '+1684', Code: 'AS', flag: '🇦🇸' },
    { name: 'Andorra', dialCode: '+376', Code: 'AD', flag: '🇦🇩' },
    { name: 'Angola', dialCode: '+244', Code: 'AO', flag: '🇦🇴' },
    { name: 'Anguilla', dialCode: '+1264', Code: 'AI', flag: '🇦🇮' },
    { name: 'Antarctica', dialCode: '+672', Code: 'AQ', flag: '🇦🇶' },
    { name: 'Antigua and Barbuda', dialCode: '+1268', Code: 'AG', flag: '🇦🇬' },
    { name: 'Argentina', dialCode: '+54', Code: 'AR', flag: '🇦🇷' },
    { name: 'Armenia', dialCode: '+374', Code: 'AM', flag: '🇦🇲' },
    { name: 'Aruba', dialCode: '+297', Code: 'AW', flag: '🇦🇼' },
    { name: 'Australia', dialCode: '+61', Code: 'AU', preferred: true, flag: '🇦🇺' },
    { name: 'Austria', dialCode: '+43', Code: 'AT', flag: '🇦🇹' },
    { name: 'Azerbaijan', dialCode: '+994', Code: 'AZ', flag: '🇦🇿' },
    { name: 'Bahamas', dialCode: '+1242', Code: 'BS', flag: '🇧🇸' },
    { name: 'Bahrain', dialCode: '+973', Code: 'BH', flag: '🇧🇭' },
    { name: 'Bangladesh', dialCode: '+880', Code: 'BD', flag: '🇧🇩' },
    { name: 'Barbados', dialCode: '+1246', Code: 'BB', flag: '🇧🇧' },
    { name: 'Belarus', dialCode: '+375', Code: 'BY', flag: '🇧🇾' },
    { name: 'Belgium', dialCode: '+32', Code: 'BE', flag: '🇧🇪' },
    { name: 'Belize', dialCode: '+501', Code: 'BZ', flag: '🇧🇿' },
    { name: 'Benin', dialCode: '+229', Code: 'BJ', flag: '🇧🇯' },
    { name: 'Bermuda', dialCode: '+1441', Code: 'BM', flag: '🇧🇲' },
    { name: 'Bhutan', dialCode: '+975', Code: 'BT', flag: '🇧🇹' },
    { name: 'Bolivia', dialCode: '+591', Code: 'BO', flag: '🇧🇴' },
    { name: 'Bosnia and Herzegovina', dialCode: '+387', Code: 'BA', flag: '🇧🇦' },
    { name: 'Botswana', dialCode: '+267', Code: 'BW', flag: '🇧🇼' },
    { name: 'Brazil', dialCode: '+55', Code: 'BR', flag: '🇧🇷' },
    { name: 'British Indian Ocean Territory', dialCode: '+246', Code: 'IO', flag: '🇮🇴' },
    { name: 'Brunei Darussalam', dialCode: '+673', Code: 'BN', flag: '🇧🇳' },
    { name: 'Bulgaria', dialCode: '+359', Code: 'BG', flag: '🇧🇬' },
    { name: 'Burkina Faso', dialCode: '+226', Code: 'BF', flag: '🇧🇫' },
    { name: 'Burundi', dialCode: '+257', Code: 'BI', flag: '🇧🇮' },
    { name: 'Cambodia', dialCode: '+855', Code: 'KH', flag: '🇰🇭' },
    { name: 'Cameroon', dialCode: '+237', Code: 'CM', flag: '🇨🇲' },
    { name: 'Canada', dialCode: '+1', Code: 'CA', flag: '🇨🇦' },
    { name: 'Cape Verde', dialCode: '+238', Code: 'CV', flag: '🇨🇻' },
    { name: 'Cayman Islands', dialCode: '+345', Code: 'KY', flag: '🇰🇾' },
    { name: 'Central African Republic', dialCode: '+236', Code: 'CF', flag: '🇨🇫' },
    { name: 'Chad', dialCode: '+235', Code: 'TD', flag: '🇹🇩' },
    { name: 'Chile', dialCode: '+56', Code: 'CL', flag: '🇨🇱' },
    { name: 'China', dialCode: '+86', Code: 'CN', flag: '🇨🇳' },
    { name: 'Christmas Island', dialCode: '+61', Code: 'CX', flag: '🇨🇽' },
    { name: 'Cocos (Keeling) Islands', dialCode: '+61', Code: 'CC', flag: '🇨🇨' },
    { name: 'Colombia', dialCode: '+57', Code: 'CO', flag: '🇨🇴' },
    { name: 'Comoros', dialCode: '+269', Code: 'KM', flag: '🇰🇲' },
    { name: 'Congo', dialCode: '+242', Code: 'CG', flag: '🇨🇬' },
    { name: 'Cook Islands', dialCode: '+682', Code: 'CK', flag: '🇨🇰' },
    { name: 'Costa Rica', dialCode: '+506', Code: 'CR', flag: '🇨🇷' },
    { name: "Cote d'Ivoire", dialCode: '+225', Code: 'CI', flag: '🇨🇮' },
    { name: 'Croatia', dialCode: '+385', Code: 'HR', flag: '🇭🇷' },
    { name: 'Cuba', dialCode: '+53', Code: 'CU', flag: '🇨🇺' },
    { name: 'Cyprus', dialCode: '+357', Code: 'CY', flag: '🇨🇾' },
    { name: 'Czech Republic', dialCode: '+420', Code: 'CZ', flag: '🇨🇿' },
    { name: 'Curaçao', dialCode: '+599', Code: 'CW', flag: '🇨🇼' },
    { name: 'Canary Islands', dialCode: '+34', Code: 'IC', flag: '🇮🇨' },
    { name: 'Denmark', dialCode: '+45', Code: 'DK', flag: '🇩🇰' },
    { name: 'Djibouti', dialCode: '+253', Code: 'DJ', flag: '🇩🇯' },
    { name: 'Dominica', dialCode: '+1767', Code: 'DM', flag: '🇩🇲' },
    { name: 'Dominican Republic', dialCode: '+1849', Code: 'DO', flag: '🇩🇴' },
    { name: 'Ecuador', dialCode: '+593', Code: 'EC', flag: '🇪🇨' },
    { name: 'Egypt', dialCode: '+20', Code: 'EG', flag: '🇪🇬' },
    { name: 'El Salvador', dialCode: '+503', Code: 'SV', flag: '🇸🇻' },
    { name: 'Equatorial Guinea', dialCode: '+240', Code: 'GQ', flag: '🇬🇶' },
    { name: 'Eritrea', dialCode: '+291', Code: 'ER', flag: '🇪🇷' },
    { name: 'Estonia', dialCode: '+372', Code: 'EE', flag: '🇪🇪' },
    { name: 'Ethiopia', dialCode: '+251', Code: 'ET', flag: '🇪🇹' },
    { name: 'Falkland Islands (Malvinas)', dialCode: '+500', Code: 'FK', flag: '🇫🇰' },
    { name: 'Faroe Islands', dialCode: '+298', Code: 'FO', flag: '🇫🇴' },
    { name: 'Fiji', dialCode: '+679', Code: 'FJ', flag: '🇫🇯' },
    { name: 'Finland', dialCode: '+358', Code: 'FI', flag: '🇫🇮' },
    { name: 'France', dialCode: '+33', Code: 'FR', flag: '🇫🇷' },
    { name: 'French Guiana', dialCode: '+594', Code: 'GF', flag: '🇬🇫' },
    { name: 'French Polynesia', dialCode: '+689', Code: 'PF', flag: '🇵🇫' },
    { name: 'Gabon', dialCode: '+241', Code: 'GA', flag: '🇬🇦' },
    { name: 'Gambia', dialCode: '+220', Code: 'GM', flag: '🇬🇲' },
    { name: 'Georgia', dialCode: '+995', Code: 'GE', flag: '🇬🇪' },
    { name: 'Germany', dialCode: '+49', Code: 'DE', flag: '🇩🇪' },
    { name: 'Ghana', dialCode: '+233', Code: 'GH', flag: '🇬🇭' },
    { name: 'Gibraltar', dialCode: '+350', Code: 'GI', flag: '🇬🇮' },
    { name: 'Greece', dialCode: '+30', Code: 'GR', flag: '🇬🇷' },
    { name: 'Greenland', dialCode: '+299', Code: 'GL', flag: '🇬🇱' },
    { name: 'Grenada', dialCode: '+1473', Code: 'GD', flag: '🇬🇩' },
    { name: 'Guadeloupe', dialCode: '+590', Code: 'GP', flag: '🇬🇵' },
    { name: 'Guam', dialCode: '+1671', Code: 'GU', flag: '🇬🇺' },
    { name: 'Guatemala', dialCode: '+502', Code: 'GT', flag: '🇬🇹' },
    { name: 'Guernsey', dialCode: '+44', Code: 'GG', flag: '🇬🇬' },
    { name: 'Guinea', dialCode: '+224', Code: 'GN', flag: '🇬🇳' },
    { name: 'Guinea-Bissau', dialCode: '+245', Code: 'GW', flag: '🇬🇼' },
    { name: 'Guyana', dialCode: '+592', Code: 'GY', flag: '🇬🇾' },
    { name: 'Haiti', dialCode: '+509', Code: 'HT', flag: '🇭🇹' },
    { name: 'Holy See (Vatican City State)', dialCode: '+379', Code: 'VA', flag: '🇻🇦' },
    { name: 'Honduras', dialCode: '+504', Code: 'HN', flag: '🇭🇳' },
    { name: 'Hong Kong', dialCode: '+852', Code: 'HK', flag: '🇭🇰' },
    { name: 'Hungary', dialCode: '+36', Code: 'HU', flag: '🇭🇺' },
    { name: 'Iceland', dialCode: '+354', Code: 'IS', flag: '🇮🇸' },
    { name: 'India', dialCode: '+91', Code: 'IN', preferred: true, flag: '🇮🇳' },
    { name: 'Indonesia', dialCode: '+62', Code: 'ID', flag: '🇮🇩' },
    { name: 'Iran', dialCode: '+98', Code: 'IR', flag: '🇮🇷' },
    { name: 'Iraq', dialCode: '+964', Code: 'IQ', flag: '🇮🇶' },
    { name: 'Ireland', dialCode: '+353', Code: 'IE', flag: '🇮🇪' },
    { name: 'Isle of Man', dialCode: '+44', Code: 'IM', flag: '🇮🇲' },
    { name: 'Israel', dialCode: '+972', Code: 'IL', flag: '🇮🇱' },
    { name: 'Italy', dialCode: '+39', Code: 'IT', flag: '🇮🇹' },
    { name: 'Jamaica', dialCode: '+1658', Code: 'JM', flag: '🇯🇲' },
    { name: 'Japan', dialCode: '+81', Code: 'JP', flag: '🇯🇵' },
    { name: 'Jersey', dialCode: '+44', Code: 'JE', flag: '🇯🇪' },
    { name: 'Jordan', dialCode: '+962', Code: 'JO', flag: '🇯🇴' },
    { name: 'Kazakhstan', dialCode: '+77', Code: 'KZ', flag: '🇰🇿' },
    { name: 'Kenya', dialCode: '+254', Code: 'KE', flag: '🇰🇪' },
    { name: 'Kiribati', dialCode: '+686', Code: 'KI', flag: '🇰🇮' },
    { name: 'Korea, ', dialCode: '+82', Code: 'KR', flag: '🇰🇷' },
    { name: 'Kuwait', dialCode: '+965', Code: 'KW', flag: '🇰🇼' },
    { name: 'Kyrgyzstan', dialCode: '+996', Code: 'KG', flag: '🇰🇬' },
    { name: 'Kosovo', dialCode: '+383', Code: 'XK', flag: '🇽🇰' },
    { name: "Lao People's Democratic Republic", dialCode: '+856', Code: 'LA', flag: '🇱🇦' },
    { name: 'Latvia', dialCode: '+371', Code: 'LV', flag: '🇱🇻' },
    { name: 'Lebanon', dialCode: '+961', Code: 'LB', flag: '🇱🇧' },
    { name: 'Lesotho', dialCode: '+266', Code: 'LS', flag: '🇱🇸' },
    { name: 'Liberia', dialCode: '+231', Code: 'LR', flag: '🇱🇷' },
    { name: 'Libyan Arab Jamahiriya', dialCode: '+218', Code: 'LY', flag: '🇱🇾' },
    { name: 'Liechtenstein', dialCode: '+423', Code: 'LI', flag: '🇱🇮' },
    { name: 'Lithuania', dialCode: '+370', Code: 'LT', flag: '🇱🇹' },
    { name: 'Luxembourg', dialCode: '+352', Code: 'LU', flag: '🇱🇺' },
    { name: 'Macao', dialCode: '+853', Code: 'MO', flag: '🇲🇴' },
    { name: 'Macedonia', dialCode: '+389', Code: 'MK', flag: '🇲🇰' },
    { name: 'Madagascar', dialCode: '+261', Code: 'MG', flag: '🇲🇬' },
    { name: 'Malawi', dialCode: '+265', Code: 'MW', flag: '🇲🇼' },
    { name: 'Malaysia', dialCode: '+60', Code: 'MY', flag: '🇲🇾' },
    { name: 'Maldives', dialCode: '+960', Code: 'MV', flag: '🇲🇻' },
    { name: 'Mali', dialCode: '+223', Code: 'ML', flag: '🇲🇱' },
    { name: 'Malta', dialCode: '+356', Code: 'MT', flag: '🇲🇹' },
    { name: 'Marshall Islands', dialCode: '+692', Code: 'MH', flag: '🇲🇭' },
    { name: 'Martinique', dialCode: '+596', Code: 'MQ', flag: '🇲🇶' },
    { name: 'Mauritania', dialCode: '+222', Code: 'MR', flag: '🇲🇷' },
    { name: 'Mauritius', dialCode: '+230', Code: 'MU', flag: '🇲🇺' },
    { name: 'Mayotte', dialCode: '+262', Code: 'YT', flag: '🇾🇹' },
    { name: 'Mexico', dialCode: '+52', Code: 'MX', flag: '🇲🇽' },
    { name: 'Micronesia', dialCode: '+691', Code: 'FM', flag: '🇫🇲' },
    { name: 'Moldova', dialCode: '+373', Code: 'MD', flag: '🇲🇩' },
    { name: 'Monaco', dialCode: '+377', Code: 'MC', flag: '🇲🇨' },
    { name: 'Mongolia', dialCode: '+976', Code: 'MN', flag: '🇲🇳' },
    { name: 'Montenegro', dialCode: '+382', Code: 'ME', flag: '🇲🇪' },
    { name: 'Montserrat', dialCode: '+1664', Code: 'MS', flag: '🇲🇸' },
    { name: 'Morocco', dialCode: '+212', Code: 'MA', flag: '🇲🇦' },
    { name: 'Mozambique', dialCode: '+258', Code: 'MZ', flag: '🇲🇿' },
    { name: 'Myanmar', dialCode: '+95', Code: 'MM', flag: '🇲🇲' },
    { name: 'Namibia', dialCode: '+264', Code: 'NA', flag: '🇳🇦' },
    { name: 'Nauru', dialCode: '+674', Code: 'NR', flag: '🇳🇷' },
    { name: 'Nepal', dialCode: '+977', Code: 'NP', flag: '🇳🇵' },
    { name: 'Netherlands', dialCode: '+31', Code: 'NL', flag: '🇳🇱' },
    { name: 'Caribbean Netherlands', dialCode: '+599', Code: 'BQ', flag: '🇧🇶' },
    { name: 'New Caledonia', dialCode: '+687', Code: 'NC', flag: '🇳🇨' },
    { name: 'New Zealand', dialCode: '+64', Code: 'NZ', flag: '🇳🇿' },
    { name: 'Nicaragua', dialCode: '+505', Code: 'NI', flag: '🇳🇮' },
    { name: 'Niger', dialCode: '+227', Code: 'NE', flag: '🇳🇪' },
    { name: 'Nigeria', dialCode: '+234', Code: 'NG', flag: '🇳🇬' },
    { name: 'Niue', dialCode: '+683', Code: 'NU', flag: '🇳🇺' },
    { name: 'Norfolk Island', dialCode: '+672', Code: 'NF', flag: '🇳🇫' },
    { name: 'Northern Mariana Islands', dialCode: '+1670', Code: 'MP', flag: '🇲🇵' },
    { name: 'Norway', dialCode: '+47', Code: 'NO', flag: '🇳🇴' },
    { name: 'Oman', dialCode: '+968', Code: 'OM', flag: '🇴🇲' },
    { name: 'Pakistan', dialCode: '+92', Code: 'PK', flag: '🇵🇰' },
    { name: 'Palau', dialCode: '+680', Code: 'PW', flag: '🇵🇼' },
    { name: 'Palestinian Territory', dialCode: '+970', Code: 'PS', flag: '🇵🇸' },
    { name: 'Panama', dialCode: '+507', Code: 'PA', flag: '🇵🇦' },
    { name: 'Papua New Guinea', dialCode: '+675', Code: 'PG', flag: '🇵🇬' },
    { name: 'Paraguay', dialCode: '+595', Code: 'PY', flag: '🇵🇾' },
    { name: 'Peru', dialCode: '+51', Code: 'PE', flag: '🇵🇪' },
    { name: 'Philippines', dialCode: '+63', Code: 'PH', flag: '🇵🇭' },
    { name: 'Pitcairn', dialCode: '+872', Code: 'PN', flag: '🇵🇳' },
    { name: 'Poland', dialCode: '+48', Code: 'PL', flag: '🇵🇱' },
    { name: 'Portugal', dialCode: '+351', Code: 'PT', flag: '🇵🇹' },
    { name: 'Puerto Rico', dialCode: '+1939', Code: 'PR', flag: '🇵🇷' },
    { name: 'Qatar', dialCode: '+974', Code: 'QA', flag: '🇶🇦' },
    { name: 'Romania', dialCode: '+40', Code: 'RO', flag: '🇷🇴' },
    { name: 'Russia', dialCode: '+7', Code: 'RU', flag: '🇷🇺' },
    { name: 'Rwanda', dialCode: '+250', Code: 'RW', flag: '🇷🇼' },
    { name: 'Réunion', dialCode: '+262', Code: 'RE', flag: '🇷🇪' },
    { name: 'Saint Barthélemy', dialCode: '+590', Code: 'BL', flag: '🇧🇱' },
    { name: 'Saint Kitts and Nevis', dialCode: '+290', Code: 'KN', flag: '🇰🇳' },
    { name: 'Saint Lucia', dialCode: '+1758', Code: 'LC', flag: '🇱🇨' },
    { name: 'Saint Martin', dialCode: '+590', Code: 'MF', flag: '🇲🇫' },
    { name: 'Saint Pierre and Miquelon', dialCode: '+508', Code: 'PM', flag: '🇵🇲' },
    { name: 'Saint Vincent and the Grenadines', dialCode: '+1784', Code: 'VC', flag: '🇻🇨' },
    { name: 'Samoa', dialCode: '+685', Code: 'WS', flag: '🇼🇸' },
    { name: 'San Marino', dialCode: '+378', Code: 'SM', flag: '🇸🇲' },
    { name: 'Sao Tome and Principe', dialCode: '+239', Code: 'ST', flag: '🇸🇹' },
    { name: 'Saudi Arabia', dialCode: '+966', Code: 'SA', flag: '🇸🇦' },
    { name: 'Senegal', dialCode: '+221', Code: 'SN', flag: '🇸🇳' },
    { name: 'Serbia', dialCode: '+381', Code: 'RS', flag: '🇷🇸' },
    { name: 'Seychelles', dialCode: '+248', Code: 'SC', flag: '🇸🇨' },
    { name: 'Sierra Leone', dialCode: '+232', Code: 'SL', flag: '🇸🇱' },
    { name: 'Singapore', dialCode: '+65', Code: 'SG', flag: '🇸🇬' },
    { name: 'Slovakia', dialCode: '+421', Code: 'SK', flag: '🇸🇰' },
    { name: 'Slovenia', dialCode: '+386', Code: 'SI', flag: '🇸🇮' },
    { name: 'Solomon Islands', dialCode: '+677', Code: 'SB', flag: '🇸🇧' },
    { name: 'Somalia', dialCode: '+252', Code: 'SO', flag: '🇸🇴' },
    { name: 'South Africa', dialCode: '+27', Code: 'ZA', flag: '🇿🇦' },
    { name: 'South Georgia and the South Sandwich Islands', dialCode: '+500', Code: 'GS', flag: '🇬🇸' },
    { name: 'Spain', dialCode: '+34', Code: 'ES', flag: '🇪🇸' },
    { name: 'Sri Lanka', dialCode: '+94', Code: 'LK', flag: '🇱🇰' },
    { name: 'Sudan', dialCode: '+249', Code: 'SD', flag: '🇸🇩' },
    { name: 'South Sudan', dialCode: '+211', Code: 'SS', flag: '🇸🇸' },
    { name: 'Suriname', dialCode: '+597', Code: 'SR', flag: '🇸🇷' },
    { name: 'Svalbard and Jan Mayen', dialCode: '+47', Code: 'SJ', flag: '🇸🇯' },
    { name: 'Swaziland', dialCode: '+268', Code: 'SZ', flag: '🇸🇿' },
    { name: 'Sweden', dialCode: '+46', Code: 'SE', flag: '🇸🇪' },
    { name: 'Switzerland', dialCode: '+41', Code: 'CH', flag: '🇨🇭' },
    { name: 'Syrian Arab Republic', dialCode: '+963', Code: 'SY', flag: '🇸🇾' },
    { name: 'Sint Maarten', dialCode: '+721', Code: 'SX', flag: '🇸🇽' },
    { name: 'Taiwan, Province of China', dialCode: '+886', Code: 'TW', flag: '🇹🇼' },
    { name: 'Tajikistan', dialCode: '+992', Code: 'TJ', flag: '🇹🇯' },
    { name: 'Tanzania', dialCode: '+255', Code: 'TZ', flag: '🇹🇿' },
    { name: 'Thailand', dialCode: '+66', Code: 'TH', flag: '🇹🇭' },
    { name: 'Timor-Leste', dialCode: '+670', Code: 'TL', flag: '🇹🇱' },
    { name: 'Togo', dialCode: '+228', Code: 'TG', flag: '🇹🇬' },
    { name: 'Tokelau', dialCode: '+690', Code: 'TK', flag: '🇹🇰' },
    { name: 'Tonga', dialCode: '+676', Code: 'TO', flag: '🇹🇴' },
    { name: 'Trinidad and Tobago', dialCode: '+1868', Code: 'TT', flag: '🇹🇹' },
    { name: 'Tunisia', dialCode: '+216', Code: 'TN', flag: '🇹🇳' },
    { name: 'Turkey', dialCode: '+90', Code: 'TR', flag: '🇹🇷' },
    { name: 'Turkmenistan', dialCode: '+993', Code: 'TM', flag: '🇹🇲' },
    { name: 'Turks and Caicos Islands', dialCode: '+1649', Code: 'TC', flag: '🇹🇨' },
    { name: 'Tuvalu', dialCode: '+688', Code: 'TV', flag: '🇹🇻' },
    { name: 'Uganda', dialCode: '+256', Code: 'UG', flag: '🇺🇬' },
    { name: 'Ukraine', dialCode: '+380', Code: 'UA', flag: '🇺🇦' },
    { name: 'United Arab Emirates', dialCode: '+971', Code: 'AE', preferred: true, flag: '🇦🇪' },
    { name: 'United Kingdom', dialCode: '+44', Code: 'GB', preferred: true, flag: '🇬🇧' },
    { name: 'United States', dialCode: '+1', Code: 'US', preferred: true, flag: '🇺🇸' },
    { name: 'Uruguay', dialCode: '+598', Code: 'UY', flag: '🇺🇾' },
    { name: 'Uzbekistan', dialCode: '+998', Code: 'UZ', flag: '🇺🇿' },
    { name: 'Vanuatu', dialCode: '+678', Code: 'VU', flag: '🇻🇺' },
    { name: 'Venezuela, Bolivarian', dialCode: '+58', Code: 'VE', flag: '🇻🇪' },
    { name: 'Viet Nam', dialCode: '+84', Code: 'VN', flag: '🇻🇳' },
    { name: 'Virgin Islands, British', dialCode: '+1284', Code: 'VG', flag: '🇻🇬' },
    { name: 'Virgin Islands, U.S.', dialCode: '+1340', Code: 'VI', flag: '🇻🇮' },
    { name: 'Wallis and Futuna', dialCode: '+681', Code: 'WF', flag: '🇼🇫' },
    { name: 'Western Sarah', dialCode: '+212', Code: 'EH', flag: '🇪🇭' },
    { name: 'Yemen', dialCode: '+967', Code: 'YE', flag: '🇾🇪' },
    { name: 'Zambia', dialCode: '+260', Code: 'ZM', flag: '🇿🇲' },
    { name: 'Zimbabwe', dialCode: '+263', Code: 'ZW', flag: '🇿🇼' },
    { name: 'Åland Islands', dialCode: '+358', Code: 'AX', flag: '🇦🇽' },
];
export default countrylist